### ISSUE TITLE
Cannot run with sound null safety, because the following dependencies don't support null safety:

### ISSUE THREAD

**Issue by YToprak** [seenickcode/fluttercrashcourse-lessons#11]
**Describe the bug**
running integration test and null safety will break test. 

Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:image_test_utils
 - package:mockito

For solutions, see https://dart.dev/go/unsound-null-safety
**To Reproduce**
1. Go to 'app_test.dart'
2. Click on 'Start Debugging '
3. Scroll down to 'Terminal'
![Bildschirmfoto 2022-01-07 um 20 43 27](https://user-images.githubusercontent.com/31251593/148598397-b01bdbb8-76cd-43fb-980f-c5c32f86877a.png)

**Comment by seenickcode** [comment]
Hello, so a few things. 

1. Your steps to reproduce do not provide the example code so I can reproduce the issue. You simply are referring to 'app_test.dart' and because this repo has over 18 of those files, I do not know where to look - but I deduced what you were referring to anyway so it's fine. Next time though, kindly provide specific steps to reproduce.

2. Your screenshot shows code outside of what is provided in this repository. You are using mockito for example. Next time, if you're running any custom code that's not exactly what is in this repository, kindly follow [our guidelines](https://fluttercrashcourse.com/reporting-issues) posted here and post the code on Stack Overflow. 

3. It appears you have a compiler issue. This repository does not use mockito nor image_test_utils. I'm not sure why you need either of those when the code we use in this repo already has mocking via `MockLocation`. Not sure why you also need image_test_utils. Are you ensuring you're calling `tester.pumpAndSettle()`? What I recommend is doing the following first:

a. check out this repository on your local machine
b. open your IDE with the repo's following Flutter project: `module02/lesson18` locationed [here](https://github.com/seenickcode/fluttercrashcourse-lessons/tree/master/module02-tourismandco/lesson18). This contains a working example of an integration test. I just updated it this morning to ensure that it uses the new way `integration_test` package works so ensure you pull from `master`.
c. Open your command line, navigate to this project above and run `flutter test integration_test` and first ensure the test runs. It works for me, just ensure you are running your simulator before running it of course. 
d. Take a look at the code to understand how it's running integration tests.
e. Try to simplify your code. Avoid using external packages unless you truly need them is my advice.

**Comment by seenickcode** [comment]
@YToprak any luck on your side? Closing for now.
